In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([5,6,7,8,9])

In [4]:
print(a.shape)

(5,)


In [5]:
print(a[3])

8


In [6]:
pd.DataFrame({'A':[2,3,4,5]})

A
0  2
1  3
2  4
3  5

In [7]:
date = pd.date_range('20231001',periods=6)

In [8]:
date

DatetimeIndex(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04',
               '2023-10-05', '2023-10-06'],
              dtype='datetime64[ns]', freq='D')

In [9]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list('ABCD'))

In [10]:
df.shape

(6, 4)

In [11]:
date

DatetimeIndex(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04',
               '2023-10-05', '2023-10-06'],
              dtype='datetime64[ns]', freq='D')

In [12]:
df.head(2)

A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119

In [13]:
df.tail(3)

A         B         C         D
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [14]:
df.to_numpy

<bound method DataFrame.to_numpy of                    A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878>

In [15]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   1.116481 -0.897513 -0.053393 -0.525608
std    1.248940  0.829629  0.690052  0.470921
min   -0.866264 -2.256904 -1.004638 -1.367119
25%    0.622928 -1.273239 -0.597264 -0.564309
50%    1.226127 -0.659165  0.189501 -0.452844
75%    1.836282 -0.475856  0.476529 -0.374506
max    2.651368  0.082836  0.592594  0.069017

In [16]:
df.T

2023-10-01  2023-10-02  2023-10-03  2023-10-04  2023-10-05  2023-10-06
A    2.651368    0.621948    1.839581   -0.866264    1.826385    0.625869
B   -0.451561   -2.256904   -0.769587    0.082836   -0.548742   -1.441124
C   -1.004638    0.592594   -0.777981    0.490667   -0.055113    0.434115
D    0.069017   -1.367119   -0.524811   -0.577476   -0.372383   -0.380878

In [17]:
df.sort_index(axis=0, ascending=True)

A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [18]:
df.sort_values(by="A")

A         B         C         D
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-06  0.625869 -1.441124  0.434115 -0.380878
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-01  2.651368 -0.451561 -1.004638  0.069017

In [19]:
a = [2,4,2,6,1,3]

In [20]:
arr = np.array(a)

In [21]:
arr.sort()

In [22]:
arr

array([1, 2, 2, 3, 4, 6])

In [23]:
arr.shape

(6,)

In [24]:
temp = arr[np.newaxis,:]
temp.shape

(1, 6)

In [25]:
temp

array([[1, 2, 2, 3, 4, 6]])

In [26]:
temp = arr[:,np.newaxis]

In [27]:
temp

array([[1],
       [2],
       [2],
       [3],
       [4],
       [6]])

In [28]:
df

A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [29]:
df.to_csv('df.csv')

In [30]:
data = pd.read_csv('df.csv')

In [31]:
data

Unnamed: 0         A         B         C         D
0  2023-10-01  2.651368 -0.451561 -1.004638  0.069017
1  2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2  2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
3  2023-10-04 -0.866264  0.082836  0.490667 -0.577476
4  2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
5  2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [32]:
df

A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [33]:
left = pd.DataFrame({'key':['A','A'], 'lval':[1,2]})
right = pd.DataFrame({'key':['A','A'], 'rval':[3,4]})

In [34]:
right

key  rval
0   A     3
1   A     4

In [35]:
pd.merge(left,right, on="key")

key  lval  rval
0   A     1     3
1   A     1     4
2   A     2     3
3   A     2     4

In [36]:
rng = pd.date_range("8/10/2002", periods=100, freq="S")

In [37]:
ts = pd.Series(np.random.randint(0,500, len(rng)), index=rng)

In [38]:
ts.resample("5Min").sum()

2002-08-10    22761
Freq: 5T, dtype: int64

In [39]:
df

A         B         C         D
2023-10-01  2.651368 -0.451561 -1.004638  0.069017
2023-10-02  0.621948 -2.256904  0.592594 -1.367119
2023-10-03  1.839581 -0.769587 -0.777981 -0.524811
2023-10-04 -0.866264  0.082836  0.490667 -0.577476
2023-10-05  1.826385 -0.548742 -0.055113 -0.372383
2023-10-06  0.625869 -1.441124  0.434115 -0.380878

In [46]:
df

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [9]:
print([i for i in reversed(range(-10, 0))])

[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]


In [11]:
str = "12345"
str[:-5]

''